# CodeRabbit configuration for HomeKeeper
# React Native + TypeScript + Expo project

# Language code for CodeRabbit interface
language: "en-US"

# Review settings
reviews:
  # High-level project context
  high_level_summary: true
  
  # Focus areas for HomeKeeper
  auto_review:
    enabled: true
    drafts: false
  
  # Path-based review rules
  path_filters:
    - "!**/*.test.{js,jsx,ts,tsx}"
    - "!**/__tests__/**"
    - "!**/node_modules/**"
    - "!**/coverage/**"
    - "!**/.expo/**"
    - "!**/.taskmaster/**"
  
  # Tool-specific configurations
  tools:
    # ESLint configuration for TypeScript and React
    eslint:
      enabled: true
      typescript_strict: true
      react_hooks: true
      react_native: true
    
# Project-specific focus areas
focus_areas:
  - "Performance optimization"
  - "React Native best practices"
  - "TypeScript type safety"
  - "Error handling"
  - "Code organization"
  - "Testing coverage"
  - "Security best practices"

# Custom instructions for HomeKeeper context
instructions: |
  This is a React Native home maintenance app called HomeKeeper.
  Focus on:
  - Mobile app performance and user experience
  - Data persistence and offline functionality  
  - Component reusability and organization
  - TypeScript type safety for data models
  - React Native navigation patterns
  - Supabase integration best practices
  - Testing strategy for mobile components 